import { Student } from '@/types/student';

export const students: Student[] = [
    {
        id: '1',
        name: 'Alice Smith',
        rollNumber: '001',
        email: 'alice@gmail.com',
        grade: 'A',
        subjects: [
          { subject: 'Mathematics', marks: 95 },
          { subject: 'Science', marks: 88 },
          { subject: 'English', marks: 92 },
          { subject: 'History', marks: 85 },
        ],
        totalMarks: 360
      },
      {
        id: '2',
        name: 'Bob Johnson',
        rollNumber: '002',
        email: 'bob@gmail.com',
        grade: 'B',
        subjects: [
          { subject: 'Mathematics', marks: 78 },
          { subject: 'Science', marks: 82 },
          { subject: 'English', marks: 75 },
          { subject: 'History', marks: 80 },
        ],
        totalMarks: 315
      },
      {
        id: '3',
        name: 'Charlie Brown',
        rollNumber: '003',
        email: 'charlie@gmail.com',
        grade: 'A-',
        subjects: [
          { subject: 'Mathematics', marks: 88 },
          { subject: 'Science', marks: 90 },
          { subject: 'English', marks: 85 },
          { subject: 'History', marks: 82 },
        ],
        totalMarks: 345
      },
      {
        id: '4',
        name: 'David Lee',
        rollNumber: '004',
        email: 'david@gmail.com',
        grade: 'B+',
        subjects: [
          { subject: 'Mathematics', marks: 85 },
          { subject: 'Science', marks: 80 },
          { subject: 'English', marks: 88 },
          { subject: 'History', marks: 78 },
        ],
        totalMarks: 331
      },
      {
        id: '5',
        name: 'Eva Garcia',
        rollNumber: '005',
        email: 'eva@gmail.com',
        grade: 'A+',
        subjects: [
          { subject: 'Mathematics', marks: 98 },
          { subject: 'Science', marks: 96 },
          { subject: 'English', marks: 95 },
          { subject: 'History', marks: 92 },
        ],
        totalMarks: 381
      },
      {
        id: '6',
        name: 'Frank Wilson',
        rollNumber: '006',
        email: 'frank@gmail.com',
        grade: 'B-',
        subjects: [
          { subject: 'Mathematics', marks: 72 },
          { subject: 'Science', marks: 75 },
          { subject: 'English', marks: 80 },
          { subject: 'History', marks: 78 },
        ],
        totalMarks: 305
      },
      {
        id: '7',
        name: 'Grace Taylor',
        rollNumber: '007',
        email: 'grace@gmail.com',
        grade: 'A',
        subjects: [
          { subject: 'Mathematics', marks: 90 },
          { subject: 'Science', marks: 92 },
          { subject: 'English', marks: 88 },
          { subject: 'History', marks: 85 },
        ],
        totalMarks: 355
      },
      {
        id: '8',
        name: 'Henry Martinez',
        rollNumber: '008',
        email: 'henry@gmail.com',
        grade: 'B+',
        subjects: [
          { subject: 'Mathematics', marks: 85 },
          { subject: 'Science', marks: 88 },
          { subject: 'English', marks: 82 },
          { subject: 'History', marks: 80 },
        ],
        totalMarks: 335
      },
      {
        id: '9',
        name: 'Isabella Clark',
        rollNumber: '009',
        email: 'isabella@gmail.com',
        grade: 'A-',
        subjects: [
          { subject: 'Mathematics', marks: 88 },
          { subject: 'Science', marks: 90 },
          { subject: 'English', marks: 92 },
          { subject: 'History', marks: 86 },
        ],
        totalMarks: 356
      },
      {
        id: '10',
        name: 'Jack Robinson',
        rollNumber: '010',
        email: 'jack@gmail.com',
        grade: 'B',
        subjects: [
          { subject: 'Mathematics', marks: 75 },
          { subject: 'Science', marks: 78 },
          { subject: 'English', marks: 80 },
          { subject: 'History', marks: 82 },
        ],
        totalMarks: 315
      },
      {
        id: '11',
        name: 'Kate Adams',
        rollNumber: '011',
        email: 'kate@gmail.com',
        grade: 'A',
        subjects: [
          { subject: 'Mathematics', marks: 92 },
          { subject: 'Science', marks: 95 },
          { subject: 'English', marks: 90 },
          { subject: 'History', marks: 88 },
        ],
        totalMarks: 365
      },
      {
        id: '12',
        name: 'Liam Wright',
        rollNumber: '012',
        email: 'liam@gmail.com',
        grade: 'B-',
        subjects: [
          { subject: 'Mathematics', marks: 70 },
          { subject: 'Science', marks: 72 },
          { subject: 'English', marks: 75 },
          { subject: 'History', marks: 78 },
        ],
        totalMarks: 295
      },
      {
        id: '13',
        name: 'Mia Turner',
        rollNumber: '013',
        email: 'mia@gmail.com',
        grade: 'A+',
        subjects: [
          { subject: 'Mathematics', marks: 98 },
          { subject: 'Science', marks: 97 },
          { subject: 'English', marks: 96 },
          { subject: 'History', marks: 95 },
        ],
        totalMarks: 386
      },
      {
        id: '14',
        name: 'Noah Harris',
        rollNumber: '014',
        email: 'noah@gmail.com',
        grade: 'B+',
        subjects: [
          { subject: 'Mathematics', marks: 85 },
          { subject: 'Science', marks: 87 },
          { subject: 'English', marks: 83 },
          { subject: 'History', marks: 80 },
        ],
        totalMarks: 335
      },
      {
        id: '15',
        name: 'Olivia Martin',
        rollNumber: '015',
        email: 'olivia@gmail.com',
        grade: 'A-',
        subjects: [
          { subject: 'Mathematics', marks: 88 },
          { subject: 'Science', marks: 90 },
          { subject: 'English', marks: 92 },
          { subject: 'History', marks: 87 },
        ],
        totalMarks: 357
      },
      {
        id: '16',
        name: 'Peter Thompson',
        rollNumber: '016',
        email: 'peter@gmail.com',
        grade: 'B',
        subjects: [
          { subject: 'Mathematics', marks: 78 },
          { subject: 'Science', marks: 80 },
          { subject: 'English', marks: 82 },
          { subject: 'History', marks: 79 },
        ],
        totalMarks: 319
      },
      {
        id: '17',
        name: 'Quinn Foster',
        rollNumber: '017',
        email: 'quinn@gmail.com',
        grade: 'A',
        subjects: [
          { subject: 'Mathematics', marks: 93 },
          { subject: 'Science', marks: 91 },
          { subject: 'English', marks: 90 },
          { subject: 'History', marks: 89 },
        ],
        totalMarks: 363
      },
    {
        id: '18',
        name: 'Rachel Cooper',
        rollNumber: '018',
        email: 'rachel@gmail.com',
        grade: 'B+',
        subjects: [
            { subject: 'Mathematics', marks: 86 },
            { subject: 'Science', marks: 88 },
            { subject: 'English', marks: 85 },
            { subject: 'History', marks: 83 },
        ],
        totalMarks: 342,
    },
    {
        id: '19',
        name: 'Samuel Baker',
        rollNumber: '019',
        email: 'samuel@gmail.com',
        grade: 'A-',
        subjects: [
            { subject: 'Mathematics', marks: 89 },
            { subject: 'Science', marks: 91 },
            { subject: 'English', marks: 88 },
            { subject: 'History', marks: 86 },
        ],
        totalMarks: 354,
    },
    {
        id: '20',
        name: 'Tara Nelson',
        rollNumber: '020',
        email: 'tara@gmail.com',
        grade: 'B',
        subjects: [
            { subject: 'Mathematics', marks: 76 },
            { subject: 'Science', marks: 79 },
            { subject: 'English', marks: 81 },
            { subject: 'History', marks: 80 },
        ],
        totalMarks: 316,
    },
    {
        id: '21',
        name: 'Ulysses King',
        rollNumber: '021',
        email: 'ulysses@gmail.com',
        grade: 'A',
        subjects: [
            { subject: 'Mathematics', marks: 94 },
            { subject: 'Science', marks: 92 },
            { subject: 'English', marks: 91 },
            { subject: 'History', marks: 90 },
        ],
        totalMarks: 367,
    },
    {
        id: '22',
        name: 'Victoria White',
        rollNumber: '022',
        email: 'victoria@gmail.com',
        grade: 'B-',
        subjects: [
            { subject: 'Mathematics', marks: 71 },
            { subject: 'Science', marks: 73 },
            { subject: 'English', marks: 76 },
            { subject: 'History', marks: 75 },
        ],
        totalMarks: 295,
    },
    {
        id: '23',
        name: 'William Green',
        rollNumber: '023',
        email: 'william@gmail.com',
        grade: 'A+',
        subjects: [
            { subject: 'Mathematics', marks: 99 },
            { subject: 'Science', marks: 98 },
            { subject: 'English', marks: 97 },
            { subject: 'History', marks: 96 },
        ],
        totalMarks: 390,
    },
    {
        id: '24',
        name: 'Xena Hall',
        rollNumber: '024',
        email: 'xena@gmail.com',
        grade: 'B+',
        subjects: [
            { subject: 'Mathematics', marks: 87 },
            { subject: 'Science', marks: 85 },
            { subject: 'English', marks: 86 },
            { subject: 'History', marks: 84 },
        ],
        totalMarks: 342,
    },
    {
        id: '25',
        name: 'Yara Scott',
        rollNumber: '025',
        email: 'yara@gmail.com',
        grade: 'A-',
        subjects: [
            { subject: 'Mathematics', marks: 90 },
            { subject: 'Science', marks: 89 },
            { subject: 'English', marks: 91 },
            { subject: 'History', marks: 88 },
        ],
        totalMarks: 358,
    },
    {
        id: '26',
        name: 'Zack Morris',
        rollNumber: '026',
        email: 'zack@gmail.com',
        grade: 'B',
        subjects: [
            { subject: 'Mathematics', marks: 77 },
            { subject: 'Science', marks: 80 },
            { subject: 'English', marks: 79 },
            { subject: 'History', marks: 81 },
        ],
        totalMarks: 317,
    },
    {
        id: '27',
        name: 'Amy Chen',
        rollNumber: '027',
        email: 'amy@gmail.com',
        grade: 'A',
        subjects: [
            { subject: 'Mathematics', marks: 95 },
            { subject: 'Science', marks: 93 },
            { subject: 'English', marks: 92 },
            { subject: 'History', marks: 91 },
        ],
        totalMarks: 371,
    },
    {
        id: '28',
        name: 'Ben Davis',
        rollNumber: '028',
        email: 'ben@gmail.com',
        grade: 'B+',
        subjects: [
            { subject: 'Mathematics', marks: 84 },
            { subject: 'Science', marks: 86 },
            { subject: 'English', marks: 85 },
            { subject: 'History', marks: 83 },
        ],
        totalMarks: 338,
    },
    {
        id: '29',
        name: 'Chloe Wilson',
        rollNumber: '029',
        email: 'chloe@gmail.com',
        grade: 'A-',
        subjects: [
            { subject: 'Mathematics', marks: 91 },
            { subject: 'Science', marks: 90 },
            { subject: 'English', marks: 89 },
            { subject: 'History', marks: 88 },
        ],
        totalMarks: 358,
    },
    {
        id: '30',
        name: 'Daniel Brown',
        rollNumber: '030',
        email: 'daniel@gmail.com',
        grade: 'B',
        subjects: [
            { subject: 'Mathematics', marks: 79 },
            { subject: 'Science', marks: 81 },
            { subject: 'English', marks: 80 },
            { subject: 'History', marks: 82 },
        ],
        totalMarks: 320,
    },
];

